// generated by vite-plugin-ssg-static-routes
import { serveStatic } from '@hono/node-server/serve-static'
import { Hono } from 'hono'
import { compress } from 'hono/compress'

const app = new Hono({ strict: false })
app.use(compress())
app.use('/admin/members/', serveStatic({ path: './dist/public/admin/members/index.html' }))
app.use('/admin/members/:memberId', serveStatic({ path: './dist/public/admin/members/$memberId/index.html' }))
app.use('/admin/members', serveStatic({ path: './dist/public/admin/members/index.html' }))
app.use('/admin/', serveStatic({ path: './dist/public/admin/index.html' }))
app.use('/admin', serveStatic({ path: './dist/public/admin/index.html' }))
app.use('/lazy-component', serveStatic({ path: './dist/public/lazy-component/index.html' }))
app.use('/redirect', serveStatic({ path: './dist/public/redirect/index.html' }))
app.use('/signin', serveStatic({ path: './dist/public/signin/index.html' }))
app.use('/', serveStatic({ path: './dist/public/index.html' }))

export default app
