// generated by vite-plugin-ssg-static-routes
export const staticRoutes = {
  '/admin/members': '/admin/members.html',
  '/admin/members/:memberId': '/admin/members/$memberId.html',
  '/admin': '/admin.html',
  '/lazy-component': '/lazy-component.html',
  '/redirect': '/redirect.html',
  '/signin': '/signin.html',
  '/': '/index.html',
}
